name: NgocPlugin
main: com.craftvn.ngoc.NgocPlugin
version: 1.0.0
api-version: 1.21
commands:
  muangoc:
    description: Mở cửa hàng ngọc
    usage: /muangoc
    permission: ngoc.use
  layngoc:
    description: Admin lấy ngọc trực tiếp
    usage: /layngoc <loai> <soluong>
    permission: ngoc.admin
permissions:
  ngoc.use:
    description: Cho phép dùng lệnh /muangoc
    default: true
  ngoc.admin:
    description: Cho phép dùng lệnh /layngoc
    default: op
