name: Build NgocPlugin

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'   # cache theo pom.xml

      - name: Build with Maven
        run: mvn -U -B -e -X clean package
        env:
          MAVEN_OPTS: -Xmx1g

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: NgocPlugin
          path: target/*.jar
          
