name: Build (Java 21 / Paper 1.21.1)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: NgocPlugin-jar
          path: target/*.jar
          
