name: Build NgocPlugin

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Temurin) with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Show versions
        run: |
          java -version
          mvn -v

      - name: Build with Maven
        run: mvn -U -B -DskipTests clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: NgocPlugin-${{ github.run_number }}
          path: |
            target/*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
            
